name: SpiggGraves
main: com.deadshotmdf.SpiggGraves.SP
author: DeadshotMDF
version: '${project.version}'
api-version: '1.20'
depend: [DecentHolograms, Vault]
softdepend: [MythicMobs]
commands:
  spigggravesreload:
  sgraves:

