name: SpiggGraves
main: com.deadshotmdf.SpiggGraves.SP
author: DeadshotMDF
version: '1.0'
api-version: '1.20'
depend: [DecentHolograms, Vault]
softdepend: [MythicMobs]
commands:
  spigggravesreload:
  sgraves:

